name = "Cactus"
license = "MIT"
licenselink = "https://github.com/augustebaum/hugo-theme-cactus/blob/master/LICENSE"
description = "A clean, responsive hugo theme for personal blog. Forked from hexo theme cactus created by @probberechts."
homepage = "https://github.com/augustebaum/hugo-theme-cactus"
# demosite = "https://www.takuzen.me/hugo-theme-cactus/"
tags = ["blog", "responsive", "clean"]
features = ["mathjax", "customizable", "color"]
min_version = "0.55"

# If the theme has a single author
[author]
    name = "Auguste Baum"
    homepage = "https://github.com/augustebaum"

# If porting an existing theme
[original]
    author = "Zeran Wu"
    homepage = "https://github.com/monkeyWzr"
    repo = "https://github.com/monkeyWzr/hugo-theme-cactus"
